export const products = [
  {
    label: "Calabrese Broccoli",
    name: "broccoli",
    priceDiscount: "21.00",
    priceOld: "25.00",
    category: "vegetable",
    image: "/food-images/broccoli.png",
  },
  {
    label: "Fresh Corn",
    name: "corn",
    priceDiscount: "21.23",
    priceOld: "18.00",
    category: "vegetable",
    image: "/food-images/corn.png",
  },
  {
    label: "Dried Pistachio",
    name: "pistachio",
    priceDiscount: "48.00",
    priceOld: "61.00",
    category: "mill",
    image: "/food-images/pistachio.png",
  },
  {
    label: "Vegan Red Tomato",
    name: "tomato",
    priceDiscount: "14.00",
    priceOld: "9.37",
    category: "vegetable",
    image: "/food-images/tomato.png",
  },
  {
    label: "Organic Almonds",
    name: "almonds",
    priceDiscount: "21.00",
    priceOld: "18.00",
    category: "fru",
    image: "/food-images/almonds.png",
  },
  {
    label: "Brown Hazelnut",
    name: "hazelnut",
    priceDiscount: "43.00",
    priceOld: "34.00",
    category: "mill",
    image: "/food-images/hazelnut.png",
  },
];
